# MAINNET
# This is the `transaction_version` field of `Runtime`
APPVERSION_M=1
# This is the `spec_version` field of `Runtime`
APPVERSION_N=108
# This is the patch version of this release
APPVERSION_P=0

# TESTNET
# This is the `transaction_version` field of `Runtime`
APPVERSION_TM=1
# This is the `spec_version` field of `Runtime`
APPVERSION_TN=144
# This is the patch version of this release
APPVERSION_TP=0